os:
  - linux
  - osx

language: go

go:
    - 1.9.2

install: true

before_install:
   - make deps

script:
  - go test -v
  - go vet ./...

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
